### ISSUE TITLE
Failed Task & PHP error 400

### ISSUE THREAD

**Issue by jeremyfrank** [pixelandtonic/AppleNews#6]
I'm currently getting a failed task showing PHP error code 400 in the stack trace below. Currently on v1.0.2. Any ideas on how best to troubleshoot this?

```
2018/01/11 19:29:02 [error] [php] Array
(
    [code] => 400
    [message] => HTTP/1.1 400 Bad Request
    [response] => stdClass Object
        (
            [errors] => Array
                (
                    [0] => stdClass Object
                        (
                            [code] => INVALID_DOCUMENT
                            [keyPath] => Array
                                (
                                    [0] => components
                                    [1] => 3
                                    [2] => text
                                )

                            [message] => "text" was null should be not (null or an empty string)
                        )

                )

        )

)
 in /storage/av04810/www/app/releases/1515524613/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Base.php on line 197 (/storage/av04810/www/app/releases/1515524613/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Base.php:289)
Stack trace:
#0 /storage/av04810/www/app/releases/1515524613/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Base.php(197): ChapterThree\AppleNewsAPI\PublisherAPI->triggerError()
#1 /storage/av04810/www/app/releases/1515524613/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Curl.php(104): ChapterThree\AppleNewsAPI\PublisherAPI->onErrorResponse()
#2 /storage/av04810/www/app/releases/1515524613/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Curl.php(88): ChapterThree\AppleNewsAPI\PublisherAPI->response()
#3 /storage/av04810/www/app/releases/1515524613/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Curl.php(242): ChapterThree\AppleNewsAPI\PublisherAPI->request()
#4 /storage/av04810/www/app/releases/1515524613/craft/plugins/applenews/services/AppleNews_ApiService.php(153): ChapterThree\AppleNewsAPI\PublisherAPI->post()
#5 /storage/av04810/www/app/releases/1515524613/craft/plugins/applenews/services/AppleNews_ApiService.php(89): Craft\AppleNews_ApiService->post()
#6 /storage/av04810/www/app/releases/1515524613/craft/plugins/applenews/services/AppleNewsService.php(341): Craft\AppleNews_ApiService->createArticle()
#7 /storage/av04810/www/app/releases/1515524613/craft/plugins/applenews/tasks/AppleNews_PostQueuedArticlesTask.php(91): Craft\AppleNewsService->postArticle()
#8 /storage/av04810/www/app/releases/1515524613/craft/app/services/TasksService.php(239): Craft\AppleNews_PostQueuedArticlesTask->runStep()
#9 /storage/av04810/www/app/releases/1515524613/craft/app/services/TasksService.php(200): Craft\TasksService->runTask()
#10 /storage/av04810/www/app/releases/1515524613/craft/app/controllers/TasksController.php(89): Craft\TasksService->runPendingTasks()
#11 /storage/av04810/www/app/releases/1515524613/craft/app/framework/web/actions/CInlineAction.php(49): Craft\TasksController->actionRerunTask()
#12 /storage/av04810/www/app/releases/1515524613/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams()
#13 /storage/av04810/www/app/releases/1515524613/craft/app/framework/web/CController.php(286): Craft\TasksController->runAction()
#14 /storage/av04810/www/app/releases/1515524613/craft/app/framework/web/CController.php(265): Craft\TasksController->runActionWithFilters()
#15 /storage/av04810/www/app/releases/1515524613/craft/app/framework/web/CWebApplication.php(282): Craft\TasksController->run()
#16 /storage/av04810/www/app/releases/1515524613/craft/app/etc/web/WebApp.php(823): Craft\WebApp->runController()
#17 /storage/av04810/www/app/releases/1515524613/craft/app/etc/web/WebApp.php(287): Craft\WebApp->_processActionRequest()
#18 /storage/av04810/www/app/releases/1515524613/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#19 /storage/av04810/www/app/releases/1515524613/craft/app/index.php(62): Craft\WebApp->run()
#20 /storage/av04810/www/app/releases/1515524613/public/index.php(14): require_once()
REQUEST_URI=/index.php?p=admin/actions/tasks/rerunTask
2018/01/11 19:29:02 [error] [application] Encountered an error running task 139 (AppleNews_PostQueuedArticles), step 1 of 2: Array
(
    [code] => 400
    [message] => HTTP/1.1 400 Bad Request
    [response] => stdClass Object
        (
            [errors] => Array
                (
                    [0] => stdClass Object
                        (
                            [code] => INVALID_DOCUMENT
                            [keyPath] => Array
                                (
                                    [0] => components
                                    [1] => 3
                                    [2] => text
                                )

                            [message] => "text" was null should be not (null or an empty string)
                        )

                )

        )

)
 in /storage/av04810/www/app/releases/1515524613/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Base.php on line 197 on line 289 of /storage/av04810/www/app/releases/1515524613/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Base.php
```

**Comment by brandonkelly** [comment]
You should have a log message that starts with `Posting entry` shortly before that error, which will include the entry’s ID and edit URL. Copy the edit URL and go to it in your browser and you can download the Apple News Format article from the Apple News widget in the sidebar. Open and prettify the article JSON, and then you should be able to find the issue by looking at the 3rd component.

**Comment by jeremyfrank** [comment]
Thank you. That's what I ended up doing, but I forgot to post the results back here. There was an empty heading tag in the rich text editor, which produced a heading object without a title in article.json.
